<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php echo $this->pageTitle('Articles'); ?>
<div class="btn-toolbar">
    <div class="btn-group pull-right">
        <?php echo $this->ctrlButton('link', array(
        'value' => 'add article',
        'url' => $this->url('ctrl_blog/default', array('controller' => 'article', 'action' => 'edit'))
        ), 'primary') ?>
        <?php echo $this->ctrlButton('link', array(
        'value' => 'manage articles',
        'url' => $this->url('ctrl_blog/default', array('controller' => 'article', 'action' => 'index'))
    )) ?>
    </div>
</div>
<div class="clearfix"></div>

<?php foreach ($this->articles as $article): ?>
    <p>
        <h1 class="page-header"><?php echo $article->getTitle(); ?></h1>
    </p>
    <p>
        <?php echo $article->getContent(true); ?>
    </p>
<?php endforeach; ?>
