<?php
/** @var $this \Ctrl\View\PhpView */
echo $this->pageTitle('Edit item', $article->getTitle());

/** @var $elems \Ctrl\Form\Element\Element[] */
$elems = $form->getElements();
$title = $elems[\CtrlBlog\Form\Article\Edit::ELEM_TITLE];
$content = $elems[\CtrlBlog\Form\Article\Edit::ELEM_CONTENT];
$content->setAttribute('id', 'article-edit-content');
$content->setAttribute('width', '80');
echo $this->ctrlForm()->start($form->setLabel('Please make your changes'));
?>

<!--<div class="btn-toolbar">-->
<!--    <div class="btn-group pull-right">-->
<!--        --><?php //echo $this->ctrlButton('link', array(
//        'value' => 'add article',
//        'url' => $this->url('ctrl_blog', array('controller' => 'article', 'action' => 'edit'))
//    ), 'primary') ?>
<!--        --><?php //echo $this->ctrlButton('link', array(
//        'value' => 'manage articles',
//        'url' => $this->url('ctrl_blog', array('controller' => 'article', 'action' => 'index'))
//    )) ?>
<!--    </div>-->
<!--</div>-->
<!--<div class="clearfix"></div>-->

<div class="row">
    <div class="span6">
        <label>Article title</label>
    </div>
    <div class="span6">
        <label>URL slug</label>
    </div>
</div>
<div class="row">
    <div class="span6">
        <?php echo $this->ctrlFormInput($title, array('bare' => true)); ?>
    </div>
    <div class="span6">
        <?php echo $this->ctrlFormInput($title, array('bare' => true)); ?>
    </div>
</div>
<div class="row article-text-editor-preview">
    <div class="span12">
        <div class="row">
            <div class="span6">
                <label>edit your article</label>
            </div>
            <div class="span6">
                <label>article preview</label>
            </div>
        </div>
        <div class="row">
            <div class="span6">
                <?php echo $this->ctrlFormInput($content, array('bare' => true, 'class' => 'text-editor-full')); ?>
            </div>
            <div class="span6">
                <div id="article-edit-content-representation"></div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->ctrlForm()->end($form, true); ?>
<script type="text/javascript">
$(function () {
    var article = $('textarea#article-edit-<?php echo \CtrlBlog\Form\Article\Edit::ELEM_CONTENT; ?>');
    function renderContent(src) {
        var dest = $('#article-edit-content-representation');
        $.ajax({
            url: '<?php echo $this->url('ctrl_blog', array(
                'controller' => 'article',
                'action' => 'render-markdown',
            )); ?>',
            type: 'POST',
            data: {
                format: 'html',
                markdown: src
            },
            success: function (result) {
                dest.html(result);
                article.css({ minHeight: (dest.height()+150)+'px' });
            }
        });
    }
    setInterval(function () {
        renderContent(article.val());
    }, 2000);
});
</script>