<?php $articles = $this->articles; /** @var $articles \CtrlBlog\Domain\Article[] */ ?>
<?php echo $this->pageTitle('Articles'); ?>
<div class="btn-toolbar">
    <div class="btn-group pull-right">
        <?php echo $this->ctrlButton('link', array(
        'value' => 'add article',
        'url' => $this->url('ctrl_blog/default', array('controller' => 'article', 'action' => 'edit'))
        ), 'primary') ?>
    </div>
</div>
<div class="clearfix"></div>
<p></p>
<table class="table table-striped">
    <tr>
        <th>id</th>
        <th>date created</th>
        <th>title</th>
        <th>actions</th>
    </tr>
    <?php foreach ($articles as $a): ?>
    <tr>
        <td><?php echo $a->getId(); ?></td>
        <td><?php echo $a->getDateCreated()->format('Y-m-d'); ?></td>
        <td><?php echo $a->getTitle(); ?></td>
        <td>
            <?php echo $this->ctrlButton('link', array('value' => 'edit',
            'href' => $this->url('ctrl_blog/default/id', array(
                'controller' => 'article',
                'action' => 'edit',
                'id' => $a->getId()
            ))), 'info') ?>
    </tr>
    <?php endforeach; ?>
</table>