<?php $articles = $this->articles; /** @var $articles \Ctrl\Blog\Domain\Article[] */ ?>
<?php echo $this->pageTitle('Articles'); ?>
<div class="btn-group">
    <a class="btn btn-primary" data-toggle="dropdown" href="#">New article</a>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>title</th>
            <th>actions</th>
        </tr>
        <?php foreach ($articles as $a): ?>
        <tr>
            <td><?php echo $a->getId(); ?></td>
            <td><?php echo $a->getTitle(); ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'article',
                    'action' => 'edit',
                    'id' => $a->getId()
                ))), 'info') ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>